#!/usr/bin/env bash
# configure nginx server so that /redirect_me
# redirects to another page

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
string_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
