#!/usr/bin/env bash
# configure Nginx so that ts HTTP response contains a
# custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

sudo echo "Hello World!" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

string_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
