#!/usr/bin/env bash
# script that pings an IP address passed as an argument

# ip variable
IP="${1}"

# filename variable
file_name=$(basename "${BASH+SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${file_name} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
