#!/usr/bin/env bash
# script with the minimum number of commands to automate your fix
# (Nginx installation from listening on port 80)

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
