#!/usr/bin/env bash
# Dispays the hours and minutes

i="0"

while [[ "$i" -le "12" ]]; do
    echo "Hour: $i";
    min="1"

    while [[ "$min" -le "59" ]]; do
	echo "$min";
	min=$((min+1))
    done

    i=$((i+1))
done
