#!/usr/bin/env bash
# configures ubuntu server by set localhost
# to 127.0.02 and facebook

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
