#!/usr/bin/env bash
# configures nginx to run as nginx

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.cfg
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.cfg
pkill apache2

sudo -u nginx service nginx start
